Repository THE-T-DEPth/spill-the-tea-server, pull requests merged in 2024-12, with the labels that each got.

#4 Feat/#3 login register
  .gitignore
  build.gradle
  src/main/java/the_t/mainproject/domain/auth/application/AuthService.java
  src/main/java/the_t/mainproject/domain/auth/application/AuthServiceImpl.java
  src/main/java/the_t/mainproject/domain/auth/domain/RefreshToken.java
  src/main/java/the_t/mainproject/domain/auth/domain/repository/RefreshTokenRepository.java
  src/main/java/the_t/mainproject/domain/auth/dto/mapper/MemberAuthMapper.java
  src/main/java/the_t/mainproject/domain/auth/dto/request/JoinReq.java
  src/main/java/the_t/mainproject/domain/auth/dto/request/LoginReq.java
  src/main/java/the_t/mainproject/domain/auth/dto/response/LoginRes.java
  src/main/java/the_t/mainproject/domain/auth/exception/RefreshTokenNotFoundException.java
  src/main/java/the_t/mainproject/domain/auth/presentation/AuthController.java
  src/main/java/the_t/mainproject/domain/member/domain/Member.java
  src/main/java/the_t/mainproject/domain/member/domain/repository/MemberRepository.java
  src/main/java/the_t/mainproject/domain/post/domain/VoiceType.java
  src/main/java/the_t/mainproject/global/config/SecurityConfig.java
  src/main/java/the_t/mainproject/global/security/UserDetailsImpl.java
  src/main/java/the_t/mainproject/global/security/UserDetailsServiceImpl.java
  src/main/java/the_t/mainproject/global/security/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/the_t/mainproject/global/security/jwt/JwtTokenProvider.java
  src/main/java/the_t/mainproject/global/security/jwt/JwtTokenProviderImpl.java
  src/main/resources/application.yml
  src/main/resources/db.migration/V1__init.sql
Labels: 🛠️ 리팩토링, :rainbow: 기능

#7 V.1.0.0 Deploy
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/cicd.yml
  .gitignore
  Dockerfile
  README.md
  build.gradle
  settings.gradle
  src/main/java/the_t/mainproject/domain/TestController.java
  src/main/java/the_t/mainproject/domain/auth/application/AuthService.java
  src/main/java/the_t/mainproject/domain/auth/application/AuthServiceImpl.java
  src/main/java/the_t/mainproject/domain/auth/domain/RefreshToken.java
  src/main/java/the_t/mainproject/domain/auth/domain/repository/RefreshTokenRepository.java
  src/main/java/the_t/mainproject/domain/auth/dto/mapper/MemberAuthMapper.java
  src/main/java/the_t/mainproject/domain/auth/dto/request/JoinReq.java
  src/main/java/the_t/mainproject/domain/auth/dto/request/LoginReq.java
  src/main/java/the_t/mainproject/domain/auth/dto/response/LoginRes.java
  src/main/java/the_t/mainproject/domain/auth/exception/RefreshTokenNotFoundException.java
  src/main/java/the_t/mainproject/domain/auth/presentation/AuthController.java
  src/main/java/the_t/mainproject/domain/block/domain/Block.java
  src/main/java/the_t/mainproject/domain/comment/domain/Comment.java
  src/main/java/the_t/mainproject/domain/commentreport/CommentReport.java
  src/main/java/the_t/mainproject/domain/commentreport/repository/CommentReportRepository.java
  src/main/java/the_t/mainproject/domain/common/BaseEntity.java
  src/main/java/the_t/mainproject/domain/keyword/domain/Keyword.java
  src/main/java/the_t/mainproject/domain/liked/domain/Liked.java
  src/main/java/the_t/mainproject/domain/member/domain/Member.java
  src/main/java/the_t/mainproject/domain/member/domain/repository/MemberRepository.java
  src/main/java/the_t/mainproject/domain/post/domain/Post.java
  src/main/java/the_t/mainproject/domain/post/domain/VoiceType.java
  src/main/java/the_t/mainproject/domain/postkeyword/PostKeyword.java
  src/main/java/the_t/mainproject/domain/postkeyword/repository/PostKeywordRepository.java
  src/main/java/the_t/mainproject/domain/postreport/PostReport.java
  src/main/java/the_t/mainproject/domain/postreport/repository/PostReportRepository.java
  src/main/java/the_t/mainproject/global/common/Message.java
  src/main/java/the_t/mainproject/global/common/SuccessResponse.java
  src/main/java/the_t/mainproject/global/config/SecurityConfig.java
  src/main/java/the_t/mainproject/global/exception/BusinessException.java
  src/main/java/the_t/mainproject/global/exception/ErrorCode.java
  src/main/java/the_t/mainproject/global/exception/ErrorResponse.java
  src/main/java/the_t/mainproject/global/exception/GlobalExceptionHandler.java
  src/main/java/the_t/mainproject/global/security/AuthenticationEntryPointImpl.java
  src/main/java/the_t/mainproject/global/security/UserDetailsImpl.java
  src/main/java/the_t/mainproject/global/security/UserDetailsServiceImpl.java
  src/main/java/the_t/mainproject/global/security/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/the_t/mainproject/global/security/jwt/JwtTokenProvider.java
  src/main/java/the_t/mainproject/global/security/jwt/JwtTokenProviderImpl.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/main/resources/db.migration/V1__init.sql
Labels: 🔖버전, :earth_americas: 인프라

#8 v1.0.1 Deploy
  .github/workflows/cicd.yml
Labels: 🔖버전, :earth_americas: 인프라

#9 v1.0.2 Display
  .github/workflows/cicd.yml
Labels: 🔖버전, :earth_americas: 인프라

#12 [FEAT] 이메일 & 닉네임 중복 체크 api
  src/main/java/the_t/mainproject/domain/auth/application/AuthService.java
  src/main/java/the_t/mainproject/domain/auth/application/AuthServiceImpl.java
  src/main/java/the_t/mainproject/domain/auth/dto/response/DuplicateCheckRes.java
  src/main/java/the_t/mainproject/domain/auth/presentation/AuthController.java
  src/main/java/the_t/mainproject/domain/member/domain/repository/MemberRepository.java
  src/main/resources/application.yml
Labels: :rainbow: 기능

#14 [FEAT]: 게시글 등록 API
  .gitignore
  build.gradle
  src/main/java/the_t/mainproject/domain/keyword/domain/repository/KeywordRepository.java
  src/main/java/the_t/mainproject/domain/keyword/service/KeywordService.java
  src/main/java/the_t/mainproject/domain/post/application/PostService.java
  src/main/java/the_t/mainproject/domain/post/application/PostServiceImpl.java
  src/main/java/the_t/mainproject/domain/post/domain/VoiceType.java
  src/main/java/the_t/mainproject/domain/post/domain/repository/PostRepository.java
  src/main/java/the_t/mainproject/domain/post/dto/req/CreatePostReq.java
  src/main/java/the_t/mainproject/domain/post/presentation/PostController.java
  src/main/java/the_t/mainproject/global/config/S3Config.java
  src/main/java/the_t/mainproject/global/config/SecurityConfig.java
  src/main/java/the_t/mainproject/global/config/SwaggerConfig.java
  src/main/java/the_t/mainproject/global/service/S3Service.java
  src/main/resources/application.yml
Labels: :rainbow: 기능

#15 [FEAT]: 게시글 상세조회, 수정, 삭제 API
  src/main/java/the_t/mainproject/domain/post/application/PostService.java
  src/main/java/the_t/mainproject/domain/post/application/PostServiceImpl.java
  src/main/java/the_t/mainproject/domain/post/domain/Post.java
  src/main/java/the_t/mainproject/domain/post/dto/req/PostReq.java
  src/main/java/the_t/mainproject/domain/post/dto/res/PostDetailRes.java
  src/main/java/the_t/mainproject/domain/post/presentation/PostController.java
  src/main/java/the_t/mainproject/domain/postkeyword/repository/PostKeywordRepository.java
Labels: :rainbow: 기능
