Repository THE-T-DEPth/spill-the-tea-server, pull requests merged in 2025-01, with the labels that each got.

#16 [FEAT]: 이메일 인증을 통한 회원가입
  .github/workflows/cicd.yml
  .gitignore
  build.gradle
  src/main/java/the_t/mainproject/domain/auth/application/AuthServiceImpl.java
  src/main/java/the_t/mainproject/domain/auth/dto/request/JoinReq.java
  src/main/java/the_t/mainproject/domain/auth/dto/request/LoginReq.java
  src/main/java/the_t/mainproject/domain/auth/dto/response/DuplicateCheckRes.java
  src/main/java/the_t/mainproject/domain/auth/dto/response/LoginRes.java
  src/main/java/the_t/mainproject/domain/auth/presentation/AuthController.java
  src/main/java/the_t/mainproject/global/config/SecurityConfig.java
  src/main/java/the_t/mainproject/infrastructure/mail/MailConfig.java
  src/main/java/the_t/mainproject/infrastructure/mail/MailUtil.java
  src/main/java/the_t/mainproject/infrastructure/mail/application/MailService.java
  src/main/java/the_t/mainproject/infrastructure/mail/dto/MailCodeRes.java
  src/main/java/the_t/mainproject/infrastructure/mail/presentation/MailController.java
  src/main/java/the_t/mainproject/infrastructure/redis/RedisConfig.java
  src/main/java/the_t/mainproject/infrastructure/redis/RedisUtil.java
  src/main/resources/application.yml
Labels: :rainbow: 기능, :earth_americas: 인프라

#17 v2.0.0 display
  .github/workflows/cicd.yml
  .gitignore
  build.gradle
  src/main/java/the_t/mainproject/domain/auth/application/AuthService.java
  src/main/java/the_t/mainproject/domain/auth/application/AuthServiceImpl.java
  src/main/java/the_t/mainproject/domain/auth/dto/request/JoinReq.java
  src/main/java/the_t/mainproject/domain/auth/dto/request/LoginReq.java
  src/main/java/the_t/mainproject/domain/auth/dto/response/DuplicateCheckRes.java
  src/main/java/the_t/mainproject/domain/auth/dto/response/LoginRes.java
  src/main/java/the_t/mainproject/domain/auth/presentation/AuthController.java
  src/main/java/the_t/mainproject/domain/keyword/domain/repository/KeywordRepository.java
  src/main/java/the_t/mainproject/domain/keyword/service/KeywordService.java
  src/main/java/the_t/mainproject/domain/member/domain/repository/MemberRepository.java
  src/main/java/the_t/mainproject/domain/post/application/PostService.java
  src/main/java/the_t/mainproject/domain/post/application/PostServiceImpl.java
  src/main/java/the_t/mainproject/domain/post/domain/Post.java
  src/main/java/the_t/mainproject/domain/post/domain/VoiceType.java
  src/main/java/the_t/mainproject/domain/post/domain/repository/PostRepository.java
  src/main/java/the_t/mainproject/domain/post/dto/req/PostReq.java
  src/main/java/the_t/mainproject/domain/post/dto/res/PostDetailRes.java
  src/main/java/the_t/mainproject/domain/post/presentation/PostController.java
  src/main/java/the_t/mainproject/domain/postkeyword/repository/PostKeywordRepository.java
  src/main/java/the_t/mainproject/global/config/S3Config.java
  src/main/java/the_t/mainproject/global/config/SecurityConfig.java
  src/main/java/the_t/mainproject/global/config/SwaggerConfig.java
  src/main/java/the_t/mainproject/global/service/S3Service.java
  src/main/java/the_t/mainproject/infrastructure/mail/MailConfig.java
  src/main/java/the_t/mainproject/infrastructure/mail/MailUtil.java
  src/main/java/the_t/mainproject/infrastructure/mail/application/MailService.java
  src/main/java/the_t/mainproject/infrastructure/mail/dto/MailCodeRes.java
  src/main/java/the_t/mainproject/infrastructure/mail/presentation/MailController.java
  src/main/java/the_t/mainproject/infrastructure/redis/RedisConfig.java
  src/main/java/the_t/mainproject/infrastructure/redis/RedisUtil.java
  src/main/resources/application.yml
Labels: 🔖버전, :earth_americas: 인프라

#21 [FEAT]: 프로필 이미지 변경 및 삭제 API
  src/main/java/the_t/mainproject/domain/member/application/MemberService.java
  src/main/java/the_t/mainproject/domain/member/application/MemberServiceImpl.java
  src/main/java/the_t/mainproject/domain/member/domain/Member.java
  src/main/java/the_t/mainproject/domain/member/presentation/MemberController.java
  src/main/java/the_t/mainproject/global/config/SecurityConfig.java
  src/main/java/the_t/mainproject/global/security/UserDetailsImpl.java
Labels: 🛠️ 리팩토링, :rainbow: 기능

#25 [FEAT]: 회원정보변경(닉네임, 비밀번호) API
  src/main/java/the_t/mainproject/domain/member/application/MemberService.java
  src/main/java/the_t/mainproject/domain/member/application/MemberServiceImpl.java
  src/main/java/the_t/mainproject/domain/member/domain/Member.java
  src/main/java/the_t/mainproject/domain/member/dto/MemberUpdateReq.java
  src/main/java/the_t/mainproject/domain/member/presentation/MemberController.java
  src/main/java/the_t/mainproject/domain/post/application/PostServiceImpl.java
Labels: :rainbow: 기능

#26 [FEAT] 로그아웃 API
  src/main/java/the_t/mainproject/domain/auth/application/AuthService.java
  src/main/java/the_t/mainproject/domain/auth/application/AuthServiceImpl.java
  src/main/java/the_t/mainproject/domain/auth/domain/RefreshToken.java
  src/main/java/the_t/mainproject/domain/auth/domain/repository/RefreshTokenRepository.java
  src/main/java/the_t/mainproject/domain/auth/dto/request/LogoutReq.java
  src/main/java/the_t/mainproject/domain/auth/dto/response/ReissueRes.java
  src/main/java/the_t/mainproject/domain/auth/presentation/AuthController.java
  src/main/java/the_t/mainproject/global/config/SecurityConfig.java
  src/main/java/the_t/mainproject/global/security/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/the_t/mainproject/global/security/jwt/JwtTokenProvider.java
  src/main/java/the_t/mainproject/global/security/jwt/JwtTokenProviderImpl.java
  src/main/java/the_t/mainproject/infrastructure/redis/RedisConfig.java
  src/main/resources/db.migration/V2__remove_refresh_token.sql
Labels: 🛠️ 리팩토링, :rainbow: 기능

#29 [FEAT]: 댓글, 대댓글 생성 API
  src/main/java/the_t/mainproject/domain/comment/application/CreateCommentService.java
  src/main/java/the_t/mainproject/domain/comment/application/CreateCommentServiceFactory.java
  src/main/java/the_t/mainproject/domain/comment/application/CreateCommentServiceImpl.java
  src/main/java/the_t/mainproject/domain/comment/application/CreateReplyServiceImpl.java
  src/main/java/the_t/mainproject/domain/comment/domain/Comment.java
  src/main/java/the_t/mainproject/domain/comment/domain/repository/CommentRepository.java
  src/main/java/the_t/mainproject/domain/comment/dto/request/CreateCommentReq.java
  src/main/java/the_t/mainproject/domain/comment/presentation/CommentController.java
  src/main/java/the_t/mainproject/global/config/SecurityConfig.java
Labels: :rainbow: 기능

#31 [FEAT]: 댓글 공감 및 신고 API
  src/main/java/the_t/mainproject/domain/comment/application/CommentService.java
  src/main/java/the_t/mainproject/domain/comment/domain/Comment.java
  src/main/java/the_t/mainproject/domain/comment/presentation/CommentController.java
  src/main/java/the_t/mainproject/domain/commentreport/application/CommentReportService.java
  src/main/java/the_t/mainproject/domain/commentreport/domain/CommentReport.java
  src/main/java/the_t/mainproject/domain/commentreport/domain/repository/CommentReportRepository.java
  src/main/java/the_t/mainproject/domain/commentreport/presentation/CommentReportController.java
  src/main/java/the_t/mainproject/domain/commentreport/repository/CommentReportRepository.java
  src/main/java/the_t/mainproject/global/config/SecurityConfig.java
Labels: 🛠️ 리팩토링, :rainbow: 기능

#33 [FEAT}: 댓글 목록 조회 API
  src/main/java/the_t/mainproject/domain/comment/application/CommentService.java
  src/main/java/the_t/mainproject/domain/comment/domain/repository/CommentRepository.java
  src/main/java/the_t/mainproject/domain/comment/dto/response/CommentListRes.java
  src/main/java/the_t/mainproject/domain/comment/dto/response/ReplyListRes.java
  src/main/java/the_t/mainproject/domain/comment/presentation/CommentController.java
Labels: :rainbow: 기능

#36 v2.1.1 Deploy
  src/main/java/the_t/mainproject/domain/block/application/BlockService.java
  src/main/java/the_t/mainproject/domain/block/domain/repository/BlockRepository.java
  src/main/java/the_t/mainproject/domain/block/presentation/BlockController.java
  src/main/java/the_t/mainproject/domain/comment/application/CommentService.java
  src/main/java/the_t/mainproject/domain/comment/application/CreateCommentService.java
  src/main/java/the_t/mainproject/domain/comment/application/CreateCommentServiceFactory.java
  src/main/java/the_t/mainproject/domain/comment/application/CreateCommentServiceImpl.java
  src/main/java/the_t/mainproject/domain/comment/application/CreateReplyServiceImpl.java
  src/main/java/the_t/mainproject/domain/comment/domain/Comment.java
  src/main/java/the_t/mainproject/domain/comment/domain/repository/CommentRepository.java
  src/main/java/the_t/mainproject/domain/comment/dto/request/CreateCommentReq.java
  src/main/java/the_t/mainproject/domain/comment/dto/response/CommentListRes.java
  src/main/java/the_t/mainproject/domain/comment/dto/response/ReplyListRes.java
  src/main/java/the_t/mainproject/domain/comment/presentation/CommentController.java
  src/main/java/the_t/mainproject/domain/commentreport/application/CommentReportService.java
  src/main/java/the_t/mainproject/domain/commentreport/domain/CommentReport.java
  src/main/java/the_t/mainproject/domain/commentreport/domain/repository/CommentReportRepository.java
  src/main/java/the_t/mainproject/domain/commentreport/presentation/CommentReportController.java
  src/main/java/the_t/mainproject/domain/commentreport/repository/CommentReportRepository.java
  src/main/java/the_t/mainproject/domain/post/domain/Post.java
  src/main/java/the_t/mainproject/domain/postreport/application/PostReportService.java
  src/main/java/the_t/mainproject/domain/postreport/domain/PostReport.java
  src/main/java/the_t/mainproject/domain/postreport/domain/repository/PostReportRepository.java
  src/main/java/the_t/mainproject/domain/postreport/presentation/PostReportController.java
  src/main/java/the_t/mainproject/domain/postreport/repository/PostReportRepository.java
  src/main/java/the_t/mainproject/global/config/SecurityConfig.java
Labels: 🔖버전, :earth_americas: 인프라

#38 [FEAT]: 회원 탈퇴 API
  src/main/java/the_t/mainproject/domain/auth/application/AuthService.java
  src/main/java/the_t/mainproject/domain/auth/application/AuthServiceImpl.java
  src/main/java/the_t/mainproject/domain/auth/presentation/AuthController.java
  src/main/java/the_t/mainproject/domain/block/domain/repository/BlockRepository.java
  src/main/java/the_t/mainproject/domain/comment/domain/repository/CommentRepository.java
  src/main/java/the_t/mainproject/domain/liked/domain/repository/LikedRepository.java
  src/main/java/the_t/mainproject/domain/post/domain/Post.java
  src/main/java/the_t/mainproject/domain/post/domain/repository/PostRepository.java
Labels: :rainbow: 기능

#39 v2.1.2 Deploy
  src/main/java/the_t/mainproject/domain/auth/application/AuthService.java
  src/main/java/the_t/mainproject/domain/auth/application/AuthServiceImpl.java
  src/main/java/the_t/mainproject/domain/auth/presentation/AuthController.java
  src/main/java/the_t/mainproject/domain/block/domain/repository/BlockRepository.java
  src/main/java/the_t/mainproject/domain/comment/domain/repository/CommentRepository.java
  src/main/java/the_t/mainproject/domain/liked/domain/repository/LikedRepository.java
  src/main/java/the_t/mainproject/domain/post/domain/Post.java
  src/main/java/the_t/mainproject/domain/post/domain/repository/PostRepository.java
Labels: 🔖버전, :earth_americas: 인프라

#41 [FEAT]: 프론트 cors 설정
  src/main/java/the_t/mainproject/global/config/WebMvcConfig.java
Labels: :rainbow: 기능, :earth_americas: 인프라

#42 v2.1.2 deploy
  src/main/java/the_t/mainproject/global/config/WebMvcConfig.java
Labels: 🔖버전, :earth_americas: 인프라

#44 [REFACTOR]: 공감순 댓글 목록 조회 관련 수정
  src/main/java/the_t/mainproject/domain/comment/application/CommentService.java
Labels: 🛠️ 리팩토링, :rainbow: 기능

#45 v2.1.3 Deploy
  src/main/java/the_t/mainproject/domain/comment/application/CommentService.java
Labels: 🔖버전, :earth_americas: 인프라

#47 v2.1.5 Deploy
  build.gradle
  src/main/java/the_t/mainproject/domain/post/application/PostService.java
  src/main/java/the_t/mainproject/domain/post/application/PostServiceImpl.java
  src/main/java/the_t/mainproject/domain/post/domain/VoiceType.java
  src/main/java/the_t/mainproject/domain/post/domain/repository/PostRepository.java
  src/main/java/the_t/mainproject/domain/post/dto/req/PostReq.java
  src/main/java/the_t/mainproject/domain/post/presentation/PostController.java
  src/main/resources/schema.sql
Labels: 🔖버전, :earth_americas: 인프라

#49 [REFACTOR]: post voice_type enum 수정
  src/main/resources/db.migration/V3__update_post_voice_type_enum.sql
Labels: 🛠️ 리팩토링, :earth_americas: 인프라

#50 v2.1.6 Deploy
  src/main/resources/db.migration/V3__update_post_voice_type_enum.sql
Labels: 🔖버전, :earth_americas: 인프라

#52 [REFACTOR]: 프로필 이미지 변경 api 수정
  src/main/java/the_t/mainproject/domain/member/application/MemberService.java
  src/main/java/the_t/mainproject/domain/member/application/MemberServiceImpl.java
  src/main/java/the_t/mainproject/domain/member/presentation/MemberController.java
  src/main/resources/schema.sql
Labels: 🛠️ 리팩토링

#53 v2.1.7 Deploy
  src/main/java/the_t/mainproject/domain/member/application/MemberService.java
  src/main/java/the_t/mainproject/domain/member/application/MemberServiceImpl.java
  src/main/java/the_t/mainproject/domain/member/presentation/MemberController.java
  src/main/resources/schema.sql
Labels: 🔖버전, :earth_americas: 인프라

#55 [REFACTOR]: 댓글 목록 조회 로직 수정
  src/main/java/the_t/mainproject/domain/comment/application/CommentService.java
Labels: 🛠️ 리팩토링

#56 [REFACTOR]: 공감순 추출 시 댓글만 추출
  src/main/java/the_t/mainproject/domain/comment/application/CommentService.java
Labels: 🛠️ 리팩토링

#60 v2.1.8 Deploy
  src/main/java/the_t/mainproject/domain/block/application/BlockService.java
  src/main/java/the_t/mainproject/domain/block/presentation/BlockController.java
  src/main/java/the_t/mainproject/domain/comment/application/CommentService.java
  src/main/java/the_t/mainproject/domain/comment/domain/repository/CommentRepository.java
  src/main/java/the_t/mainproject/domain/comment/dto/response/CommentListRes.java
  src/main/java/the_t/mainproject/domain/comment/dto/response/ReplyListRes.java
  src/main/java/the_t/mainproject/domain/comment/presentation/CommentController.java
  src/main/java/the_t/mainproject/domain/liked/domain/repository/LikedRepository.java
  src/main/java/the_t/mainproject/domain/post/application/PostService.java
  src/main/java/the_t/mainproject/domain/post/application/PostServiceImpl.java
  src/main/java/the_t/mainproject/domain/post/domain/repository/PostRepository.java
  src/main/java/the_t/mainproject/domain/post/dto/req/PostReq.java
  src/main/java/the_t/mainproject/domain/post/dto/res/PostListRes.java
  src/main/java/the_t/mainproject/domain/post/presentation/PostController.java
  src/main/java/the_t/mainproject/global/config/SwaggerConfig.java
Labels: 🔖버전, :earth_americas: 인프라

#62 [FEAT]: 댓글 및 대댓글 삭제
  src/main/java/the_t/mainproject/domain/comment/application/CommentService.java
  src/main/java/the_t/mainproject/domain/comment/exception/UnauthorizedException.java
  src/main/java/the_t/mainproject/domain/comment/presentation/CommentController.java
  src/main/java/the_t/mainproject/global/config/SwaggerConfig.java
Labels: :rainbow: 기능

#64 [FEAT]: 회원 정보 조회 api
  src/main/java/the_t/mainproject/domain/member/application/MemberService.java
  src/main/java/the_t/mainproject/domain/member/application/MemberServiceImpl.java
  src/main/java/the_t/mainproject/domain/member/dto/request/MemberUpdateReq.java
  src/main/java/the_t/mainproject/domain/member/dto/response/MemberInfoRes.java
  src/main/java/the_t/mainproject/domain/member/presentation/MemberController.java
Labels: :rainbow: 기능

#65 v2.1.9 Deploy
  src/main/java/the_t/mainproject/domain/comment/application/CommentService.java
  src/main/java/the_t/mainproject/domain/comment/exception/UnauthorizedException.java
  src/main/java/the_t/mainproject/domain/comment/presentation/CommentController.java
  src/main/java/the_t/mainproject/domain/member/application/MemberService.java
  src/main/java/the_t/mainproject/domain/member/application/MemberServiceImpl.java
  src/main/java/the_t/mainproject/domain/member/dto/request/MemberUpdateReq.java
  src/main/java/the_t/mainproject/domain/member/dto/response/MemberInfoRes.java
  src/main/java/the_t/mainproject/domain/member/presentation/MemberController.java
  src/main/java/the_t/mainproject/global/config/SwaggerConfig.java
Labels: 🔖버전, :earth_americas: 인프라

#66 [FEAT] 게시글-이미지 연관관계 변경 및 API 수정
  src/main/java/the_t/mainproject/domain/auth/application/AuthServiceImpl.java
  src/main/java/the_t/mainproject/domain/post/application/PostService.java
  src/main/java/the_t/mainproject/domain/post/application/PostServiceImpl.java
  src/main/java/the_t/mainproject/domain/post/domain/Image.java
  src/main/java/the_t/mainproject/domain/post/domain/Post.java
  src/main/java/the_t/mainproject/domain/post/domain/repository/ImageRepository.java
  src/main/java/the_t/mainproject/domain/post/dto/req/PostReq.java
  src/main/java/the_t/mainproject/domain/post/dto/res/ImageRes.java
  src/main/java/the_t/mainproject/domain/post/dto/res/PostDetailRes.java
  src/main/java/the_t/mainproject/domain/post/dto/res/PostListRes.java
  src/main/java/the_t/mainproject/domain/post/presentation/PostController.java
  src/main/java/the_t/mainproject/global/exception/ErrorCode.java
  src/main/java/the_t/mainproject/global/service/S3Service.java
Labels: 🛠️ 리팩토링, :rainbow: 기능

#68 [FEAT] (홈) 게시글 최신순/공감순 조회
  src/main/java/the_t/mainproject/domain/post/application/PostService.java
  src/main/java/the_t/mainproject/domain/post/application/PostServiceImpl.java
  src/main/java/the_t/mainproject/domain/post/domain/repository/PostRepository.java
  src/main/java/the_t/mainproject/domain/post/presentation/PostController.java
Labels: :rainbow: 기능

#69 [REFACTOR]: 로그인 예외처리 및 이미지 구조 변경
  src/main/java/the_t/mainproject/domain/auth/application/AuthServiceImpl.java
  src/main/java/the_t/mainproject/domain/image/domain/Image.java
  src/main/java/the_t/mainproject/domain/image/domain/repository/ImageRepository.java
  src/main/java/the_t/mainproject/domain/image/dto/ImageRes.java
  src/main/java/the_t/mainproject/domain/post/application/PostService.java
  src/main/java/the_t/mainproject/domain/post/application/PostServiceImpl.java
  src/main/java/the_t/mainproject/domain/post/domain/Post.java
  src/main/java/the_t/mainproject/domain/post/presentation/PostController.java
  src/main/java/the_t/mainproject/global/exception/GlobalExceptionHandler.java
  src/main/resources/db/migration/V1__init.sql
  src/main/resources/db/migration/V2__remove_refresh_token.sql
  src/main/resources/db/migration/V3__update_post_voice_type_enum.sql
  src/main/resources/db/migration/V4__create_image_table.sql
  src/main/resources/db/migration/V5__update_post_table.sql
  src/main/resources/db/migration/V6__update_member.sql
Labels: 🛠️ 리팩토링, :rainbow: 기능, :earth_americas: 인프라

#70 v2.1.10 Deploy
  src/main/java/the_t/mainproject/domain/auth/application/AuthServiceImpl.java
  src/main/java/the_t/mainproject/domain/image/domain/Image.java
  src/main/java/the_t/mainproject/domain/image/domain/repository/ImageRepository.java
  src/main/java/the_t/mainproject/domain/image/dto/ImageRes.java
  src/main/java/the_t/mainproject/domain/post/application/PostService.java
  src/main/java/the_t/mainproject/domain/post/application/PostServiceImpl.java
  src/main/java/the_t/mainproject/domain/post/domain/Post.java
  src/main/java/the_t/mainproject/domain/post/domain/repository/PostRepository.java
  src/main/java/the_t/mainproject/domain/post/dto/req/PostReq.java
  src/main/java/the_t/mainproject/domain/post/dto/res/PostDetailRes.java
  src/main/java/the_t/mainproject/domain/post/dto/res/PostListRes.java
  src/main/java/the_t/mainproject/domain/post/presentation/PostController.java
  src/main/java/the_t/mainproject/global/exception/ErrorCode.java
  src/main/java/the_t/mainproject/global/exception/GlobalExceptionHandler.java
  src/main/java/the_t/mainproject/global/service/S3Service.java
  src/main/resources/db/migration/V1__init.sql
  src/main/resources/db/migration/V2__remove_refresh_token.sql
  src/main/resources/db/migration/V3__update_post_voice_type_enum.sql
  src/main/resources/db/migration/V4__create_image_table.sql
  src/main/resources/db/migration/V5__update_post_table.sql
  src/main/resources/db/migration/V6__update_member.sql
Labels: 🔖버전, :earth_americas: 인프라

#71 [FEAT] 게시글 조회 시 반환값(공감여부) 추가 및 이미지 관련 로직 삭제
  src/main/java/the_t/mainproject/domain/image/domain/Image.java
  src/main/java/the_t/mainproject/domain/image/domain/repository/ImageRepository.java
  src/main/java/the_t/mainproject/domain/image/dto/ImageRes.java
  src/main/java/the_t/mainproject/domain/post/application/PostService.java
  src/main/java/the_t/mainproject/domain/post/application/PostServiceImpl.java
  src/main/java/the_t/mainproject/domain/post/domain/Post.java
  src/main/java/the_t/mainproject/domain/post/dto/req/PostReq.java
  src/main/java/the_t/mainproject/domain/post/dto/res/PostDetailRes.java
  src/main/java/the_t/mainproject/domain/post/dto/res/PostListRes.java
  src/main/java/the_t/mainproject/domain/post/presentation/PostController.java
  src/main/java/the_t/mainproject/global/service/AuthenticationService.java
Labels: 🛠️ 리팩토링, :rainbow: 기능

#73 [REFACTOR] 회원 탈퇴 로직 수정
  src/main/java/the_t/mainproject/domain/auth/application/AuthServiceImpl.java
  src/main/java/the_t/mainproject/domain/comment/domain/Comment.java
  src/main/java/the_t/mainproject/domain/commentreport/application/CommentReportService.java
  src/main/java/the_t/mainproject/domain/commentreport/domain/repository/CommentReportRepository.java
  src/main/java/the_t/mainproject/domain/post/domain/Post.java
  src/main/java/the_t/mainproject/domain/post/presentation/PostController.java
  src/main/java/the_t/mainproject/domain/postreport/application/PostReportService.java
  src/main/java/the_t/mainproject/domain/postreport/domain/repository/PostReportRepository.java
  src/main/java/the_t/mainproject/global/config/SwaggerConfig.java
  src/main/resources/db/migration/V7__remove_image.sql
Labels: 🛠️ 리팩토링, :rainbow: 기능

#74 v2.1.11 Deploy
  src/main/java/the_t/mainproject/domain/auth/application/AuthServiceImpl.java
  src/main/java/the_t/mainproject/domain/comment/domain/Comment.java
  src/main/java/the_t/mainproject/domain/commentreport/application/CommentReportService.java
  src/main/java/the_t/mainproject/domain/commentreport/domain/repository/CommentReportRepository.java
  src/main/java/the_t/mainproject/domain/image/domain/Image.java
  src/main/java/the_t/mainproject/domain/image/domain/repository/ImageRepository.java
  src/main/java/the_t/mainproject/domain/image/dto/ImageRes.java
  src/main/java/the_t/mainproject/domain/post/application/PostService.java
  src/main/java/the_t/mainproject/domain/post/application/PostServiceImpl.java
  src/main/java/the_t/mainproject/domain/post/domain/Post.java
  src/main/java/the_t/mainproject/domain/post/dto/req/PostReq.java
  src/main/java/the_t/mainproject/domain/post/dto/res/PostDetailRes.java
  src/main/java/the_t/mainproject/domain/post/dto/res/PostListRes.java
  src/main/java/the_t/mainproject/domain/post/presentation/PostController.java
  src/main/java/the_t/mainproject/domain/postreport/application/PostReportService.java
  src/main/java/the_t/mainproject/domain/postreport/domain/repository/PostReportRepository.java
  src/main/java/the_t/mainproject/global/config/SwaggerConfig.java
  src/main/java/the_t/mainproject/global/service/AuthenticationService.java
  src/main/resources/db/migration/V7__remove_image.sql
Labels: 🔖버전, :earth_americas: 인프라

#77 [CHORE]: 이메일 인증 html 적용
  build.gradle
  src/main/java/the_t/mainproject/infrastructure/mail/MailUtil.java
  src/main/resources/static/images/BigPot.png
  src/main/resources/static/images/BigPot2.png
  src/main/resources/static/images/Tea.png
  src/main/resources/static/images/Union.png
  src/main/resources/static/images/Union2.png
  src/main/resources/static/images/Union3.png
  src/main/resources/static/images/header.png
  src/main/resources/templates/verification-email.html
Labels: :rainbow: 기능, :earth_americas: 인프라

#78 [REFACTOR]: 1차 QA 내용 수정
  src/main/java/the_t/mainproject/domain/auth/application/AuthService.java
  src/main/java/the_t/mainproject/domain/auth/application/AuthServiceImpl.java
  src/main/java/the_t/mainproject/domain/auth/dto/request/JoinReq.java
  src/main/java/the_t/mainproject/domain/auth/dto/response/JoinRes.java
  src/main/java/the_t/mainproject/domain/auth/presentation/AuthController.java
  src/main/java/the_t/mainproject/domain/comment/application/CommentService.java
  src/main/java/the_t/mainproject/domain/comment/domain/Comment.java
  src/main/java/the_t/mainproject/domain/comment/domain/repository/CommentRepository.java
  src/main/java/the_t/mainproject/domain/comment/dto/response/CommentListRes.java
  src/main/java/the_t/mainproject/domain/comment/dto/response/ReplyListRes.java
  src/main/java/the_t/mainproject/domain/comment/presentation/CommentController.java
  src/main/java/the_t/mainproject/domain/commentliked/domain/CommentLiked.java
  src/main/java/the_t/mainproject/domain/commentliked/domain/repository/CommentLikedRepository.java
  src/main/java/the_t/mainproject/domain/commentreport/application/CommentReportService.java
  src/main/java/the_t/mainproject/domain/commentreport/domain/repository/CommentReportRepository.java
  src/main/java/the_t/mainproject/domain/post/dto/res/PostDetailRes.java
  src/main/java/the_t/mainproject/domain/post/dto/res/PostListRes.java
  src/main/java/the_t/mainproject/domain/postreport/application/PostReportService.java
  src/main/java/the_t/mainproject/domain/postreport/domain/repository/PostReportRepository.java
  src/main/java/the_t/mainproject/global/config/SwaggerConfig.java
  src/main/java/the_t/mainproject/global/exception/GlobalExceptionHandler.java
  src/main/resources/db/migration/V8__create_comment_liked_table.sql
Labels: 🛠️ 리팩토링, :rainbow: 기능, :earth_americas: 인프라

#79 v2.2.0 Deploy
  build.gradle
  src/main/java/the_t/mainproject/domain/auth/application/AuthService.java
  src/main/java/the_t/mainproject/domain/auth/application/AuthServiceImpl.java
  src/main/java/the_t/mainproject/domain/auth/dto/request/JoinReq.java
  src/main/java/the_t/mainproject/domain/auth/dto/response/JoinRes.java
  src/main/java/the_t/mainproject/domain/auth/presentation/AuthController.java
  src/main/java/the_t/mainproject/domain/comment/application/CommentService.java
  src/main/java/the_t/mainproject/domain/comment/domain/Comment.java
  src/main/java/the_t/mainproject/domain/comment/domain/repository/CommentRepository.java
  src/main/java/the_t/mainproject/domain/comment/dto/response/CommentListRes.java
  src/main/java/the_t/mainproject/domain/comment/dto/response/ReplyListRes.java
  src/main/java/the_t/mainproject/domain/comment/presentation/CommentController.java
  src/main/java/the_t/mainproject/domain/commentliked/domain/CommentLiked.java
  src/main/java/the_t/mainproject/domain/commentliked/domain/repository/CommentLikedRepository.java
  src/main/java/the_t/mainproject/domain/commentreport/application/CommentReportService.java
  src/main/java/the_t/mainproject/domain/commentreport/domain/repository/CommentReportRepository.java
  src/main/java/the_t/mainproject/domain/post/dto/res/PostDetailRes.java
  src/main/java/the_t/mainproject/domain/post/dto/res/PostListRes.java
  src/main/java/the_t/mainproject/domain/postreport/application/PostReportService.java
  src/main/java/the_t/mainproject/domain/postreport/domain/repository/PostReportRepository.java
  src/main/java/the_t/mainproject/global/config/SwaggerConfig.java
  src/main/java/the_t/mainproject/global/exception/GlobalExceptionHandler.java
  src/main/java/the_t/mainproject/infrastructure/mail/MailUtil.java
  src/main/resources/db/migration/V8__create_comment_liked_table.sql
  src/main/resources/static/images/BigPot.png
  src/main/resources/static/images/BigPot2.png
  src/main/resources/static/images/Tea.png
  src/main/resources/static/images/Union.png
  src/main/resources/static/images/Union2.png
  src/main/resources/static/images/Union3.png
  src/main/resources/static/images/header.png
  src/main/resources/templates/verification-email.html
Labels: 🔖버전, :earth_americas: 인프라

#80 [FEAT] 소설화 API 구현, 게시글 등록 시 반환값 추가
  src/main/java/the_t/mainproject/domain/gpt/application/GPTService.java
  src/main/java/the_t/mainproject/domain/gpt/dto/req/GPTMessage.java
  src/main/java/the_t/mainproject/domain/gpt/dto/req/GPTRequest.java
  src/main/java/the_t/mainproject/domain/gpt/dto/req/NovelizeReq.java
  src/main/java/the_t/mainproject/domain/gpt/dto/res/GPTResponse.java
  src/main/java/the_t/mainproject/domain/gpt/dto/res/NovelizeRes.java
  src/main/java/the_t/mainproject/domain/gpt/presentation/GPTController.java
  src/main/java/the_t/mainproject/domain/post/application/PostService.java
  src/main/java/the_t/mainproject/domain/post/application/PostServiceImpl.java
  src/main/java/the_t/mainproject/domain/post/presentation/PostController.java
  src/main/java/the_t/mainproject/global/config/GPTConfig.java
  src/main/java/the_t/mainproject/global/config/SecurityConfig.java
  src/main/java/the_t/mainproject/global/exception/ErrorCode.java
Labels: :rainbow: 기능

#81 v2.2.1 Deploy
  src/main/java/the_t/mainproject/domain/gpt/application/GPTService.java
  src/main/java/the_t/mainproject/domain/gpt/dto/req/GPTMessage.java
  src/main/java/the_t/mainproject/domain/gpt/dto/req/GPTRequest.java
  src/main/java/the_t/mainproject/domain/gpt/dto/req/NovelizeReq.java
  src/main/java/the_t/mainproject/domain/gpt/dto/res/GPTResponse.java
  src/main/java/the_t/mainproject/domain/gpt/dto/res/NovelizeRes.java
  src/main/java/the_t/mainproject/domain/gpt/presentation/GPTController.java
  src/main/java/the_t/mainproject/domain/post/application/PostService.java
  src/main/java/the_t/mainproject/domain/post/application/PostServiceImpl.java
  src/main/java/the_t/mainproject/domain/post/presentation/PostController.java
  src/main/java/the_t/mainproject/global/config/GPTConfig.java
  src/main/java/the_t/mainproject/global/config/SecurityConfig.java
  src/main/java/the_t/mainproject/global/config/SwaggerConfig.java
  src/main/java/the_t/mainproject/global/exception/ErrorCode.java
Labels: 🔖버전, :earth_americas: 인프라

#83 [CHORE]: 댓글 목록 조회 시 댓글 공감 반환값 추가
  src/main/java/the_t/mainproject/domain/comment/application/CommentService.java
  src/main/java/the_t/mainproject/domain/comment/dto/response/CommentListRes.java
  src/main/java/the_t/mainproject/domain/comment/dto/response/ReplyListRes.java
  src/main/java/the_t/mainproject/global/config/SwaggerConfig.java
Labels: 🛠️ 리팩토링

#84 v2.2.2 Deploy
  src/main/java/the_t/mainproject/domain/comment/application/CommentService.java
  src/main/java/the_t/mainproject/domain/comment/dto/response/CommentListRes.java
  src/main/java/the_t/mainproject/domain/comment/dto/response/ReplyListRes.java
  src/main/java/the_t/mainproject/global/config/SwaggerConfig.java
Labels: 🔖버전, :earth_americas: 인프라
